import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from "./components/banner/banner";
import NavBar from "./components/navbar/navbar";
import SectionCards from "./components/card/section-cards";
import {getPopularVideos, getVideos, getWatchItAgainVideos} from "../lib/videos";
import {verifyToken} from "../lib/utils";

export async function getServerSideProps(context) {
    /// we are not using the /api/user endpoint because this code
    /// is a server side code. so, no need to run a server side api code
    /// to get something from the server itself. hope this makes sense!
    const { token, ...user } = await verifyToken(context.req.cookies.token);
    /// no valid user per the provided token. Bail out!!
    if(!user.user_id) {
        return {
            props: {url: '/'},
            redirect: {
                destination: `/login`,
                permanent: false,
            },
        }
    }
    /// Get videos
    const disneyVideos = await getVideos(`disney trailer`);
    const productivityVideos = await getVideos(`productivity`);
    const travelVideos = await getVideos(`travel`);
    const popularVideos = await getPopularVideos();

    const watchedItAgainVideos = await getWatchItAgainVideos(user.user_id, token);
    return { props: {
        disneyVideos,
        productivityVideos,
        travelVideos,
        popularVideos,
        watchedItAgainVideos: ((videos) => videos.map(video => ({
            id: video.video_id,
            imgUrl: `https://i.ytimg.com/vi/${video.video_id}/maxresdefault.jpg`
        })))(watchedItAgainVideos),
        user,
    }};
}

export default function Home({ disneyVideos, productivityVideos, travelVideos, popularVideos, watchedItAgainVideos, user: { email }}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.main}>
            <NavBar username={email}/>
            <Banner
                title='Clifford the red dog'
                subTitle="a very cute dog"
                imgUrl={`/static/clifford.webp`}
                videoId={`4zH5iYM4wJo`}
            />
            <div className={styles.sectionWrapper}>
                { (!!watchedItAgainVideos?.length) && <SectionCards title={`Watch It Again`} videos={watchedItAgainVideos} size={`small`}/>}
                <SectionCards title={`Disney`} videos={disneyVideos} size={`large`}/>
                <SectionCards title={`Travel`} videos={travelVideos} size={`small`}/>
                <SectionCards title={`Productivity`} videos={productivityVideos} size={`medium`}/>
                <SectionCards title={`Popular`} videos={popularVideos}  size={`small`}/>
            </div>
        </div>
    </div>
  )
}
